version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "5433:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    restart: always

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=sfc_host
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: always

  jasperserver:
    image: retriever/jasperserver:7.5.0
    container_name: jasperserver
    ports:
      - 8089:8080
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
    volumes:
      - ./reports-deploy:/jasperserver-import
    restart: always

  mssql-server-linux:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
        - SA_PASSWORD=fpf@1212
        - ACCEPT_EULA=Y
    volumes:
        - mssqlsystem:/var/opt/mssql
        - mssqluser:/var/opt/sqlserver
    ports:
        - "1433:1433"
    restart: always
  
  minio:
    image: quay.io/minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "epeople"
      MINIO_ROOT_PASSWORD: "fpf@1212"
    volumes:
      - ../data:/data
    entrypoint: /bin/sh
    command: -c "mc mb /data/epeople && minio server /data --console-address ':9001'"

volumes:
  pgdata:
  jasperserver-reports:
  mssqlsystem:
  mssqluser:

networks:
  default:
