version: "2"
services:
  kibana:
    image: docker.io/bitnami/kibana:8
    restart: always
    ports:
      - "5601:5601"
    volumes:
      - "kibana_data:/bitnami/kibana"
volumes:
  kibana_data:
    driver: local

networks:
  default:
    name: elasticnet
    external: true