version: '3.9'
services:

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
      restart: always
      environment:
        - discovery.type=single-node
      ports:
        - '9200:9200'

networks:
  default:
    name: elasticnet
    external: true